# Generated by Django 5.1 on 2024-11-08 18:17

import api.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CitiesModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'cities',
            },
        ),
        migrations.CreateModel(
            name='ClientTypesModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'client_types',
            },
        ),
        migrations.CreateModel(
            name='ContactTypesModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'contact_types',
            },
        ),
        migrations.CreateModel(
            name='CountriesModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'countries',
            },
        ),
        migrations.CreateModel(
            name='ExpenseDetailsModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'expense_details',
            },
        ),
        migrations.CreateModel(
            name='InventoryTypesModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('type', models.IntegerField()),
            ],
            options={
                'db_table': 'inventory_types',
            },
        ),
        migrations.CreateModel(
            name='LocationsModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'locations',
            },
        ),
        migrations.CreateModel(
            name='PaymentMethodsModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField()),
                ('value', models.FloatField(default=0)),
                ('status', models.BooleanField(default=True)),
                ('allow_discount', models.BooleanField(default=True)),
                ('allow_note', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'payment_methods',
            },
        ),
        migrations.CreateModel(
            name='PersonsModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('identification_id', models.CharField(max_length=100)),
                ('profile_image', models.ImageField(null=True, upload_to=api.models.upload_to_profiles)),
                ('alias', models.CharField(max_length=50, null=True)),
                ('occupation', models.CharField(max_length=50, null=True)),
                ('firstname', models.CharField(max_length=50)),
                ('middlename', models.CharField(max_length=50, null=True)),
                ('lastname', models.CharField(max_length=50)),
                ('second_lastname', models.CharField(max_length=50, null=True)),
                ('mobile', models.CharField(max_length=20, null=True)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('birthdate', models.DateField(null=True)),
            ],
            options={
                'db_table': 'persons',
            },
        ),
        migrations.CreateModel(
            name='ProductBrandsModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'product_brands',
            },
        ),
        migrations.CreateModel(
            name='ProductCategoriesModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'product_categories',
            },
        ),
        migrations.CreateModel(
            name='SaleReceiptModel',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('prompter', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField()),
            ],
            options={
                'db_table': 'sale_receipt',
            },
        ),
        migrations.CreateModel(
            name='SaleStatusModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('calculate', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'sale_status',
            },
        ),
        migrations.CreateModel(
            name='SuppliersModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=100)),
                ('company_identification', models.CharField(max_length=50, null=True)),
                ('company_email', models.EmailField(max_length=254, null=True)),
                ('company_phone', models.CharField(max_length=20, null=True)),
                ('company_phone_2', models.CharField(max_length=20, null=True)),
                ('company_address', models.CharField(null=True)),
                ('advisor_fullname', models.CharField(null=True)),
                ('advisor_email', models.EmailField(max_length=254, null=True)),
                ('advisor_phone', models.CharField(max_length=20, null=True)),
                ('advisor_phone_2', models.CharField(max_length=20, null=True)),
            ],
            options={
                'db_table': 'suppliers',
            },
        ),
        migrations.CreateModel(
            name='TaxesModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField()),
                ('value', models.FloatField(default=0)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'taxes',
            },
        ),
        migrations.CreateModel(
            name='TypesIdsModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'types_ids',
            },
        ),
        migrations.CreateModel(
            name='ClientsModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('allow_credit', models.BooleanField(default=True)),
                ('note', models.CharField(max_length=100, null=True)),
                ('date_reg', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='api.clienttypesmodel')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.locationsmodel')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.personsmodel')),
            ],
            options={
                'db_table': 'clients',
            },
        ),
        migrations.CreateModel(
            name='ClientContactsModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('relationship', models.CharField(max_length=100)),
                ('fullname', models.CharField()),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='api.clientsmodel')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.contacttypesmodel')),
            ],
            options={
                'db_table': 'client_contacts',
            },
        ),
        migrations.CreateModel(
            name='CashRegisterModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('no', models.CharField(max_length=100)),
                ('amount', models.FloatField(default=0)),
                ('supplier', models.CharField(max_length=100)),
                ('description', models.CharField()),
                ('date_reg', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.locationsmodel')),
            ],
            options={
                'db_table': 'cash_register',
            },
        ),
        migrations.CreateModel(
            name='IdentificationImagesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to=api.models.upload_to_identifications)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identification_images', to='api.personsmodel')),
            ],
            options={
                'db_table': 'identification_images',
            },
        ),
        migrations.CreateModel(
            name='AddressesModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('street', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=50, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.citiesmodel')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='api.personsmodel')),
            ],
            options={
                'db_table': 'addresses',
            },
        ),
        migrations.CreateModel(
            name='ProductsModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('barcode', models.CharField(max_length=50, null=True)),
                ('name', models.CharField()),
                ('model', models.CharField(max_length=50, null=True)),
                ('note', models.CharField(max_length=100, null=True)),
                ('cost_price', models.FloatField(default=0)),
                ('cash_profit', models.FloatField(default=0)),
                ('cash_price', models.FloatField(default=0)),
                ('credit_profit', models.FloatField(default=0)),
                ('credit_price', models.FloatField(default=0)),
                ('min_stock', models.IntegerField(default=0)),
                ('date_reg', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.BooleanField(default=True)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='api.productbrandsmodel')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='api.productcategoriesmodel')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='api.suppliersmodel')),
                ('tax', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='api.taxesmodel')),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='ProductImagesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to=api.models.upload_to_products)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='product_images', to='api.productsmodel')),
            ],
            options={
                'db_table': 'product_images',
            },
        ),
        migrations.CreateModel(
            name='SalesModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('total', models.FloatField(default=0)),
                ('type', models.IntegerField(default=1)),
                ('quantity_of_payments', models.IntegerField(default=1)),
                ('payment_days', models.IntegerField(null=True)),
                ('note', models.CharField(max_length=100, null=True)),
                ('date_reg', models.DateTimeField(default=django.utils.timezone.now)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.clientsmodel')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.locationsmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.salestatusmodel')),
            ],
            options={
                'db_table': 'sales',
            },
        ),
        migrations.CreateModel(
            name='SalePaymentsModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('no', models.IntegerField(null=True, unique=True)),
                ('subtotal', models.FloatField(default=0)),
                ('commission', models.FloatField(default=0)),
                ('surcharge', models.FloatField(default=0)),
                ('discount_per', models.FloatField(default=0)),
                ('discount', models.FloatField(default=0)),
                ('total', models.FloatField(default=0)),
                ('total_paid', models.FloatField(default=0)),
                ('total_remaining', models.FloatField(default=0)),
                ('pay', models.FloatField(default=0)),
                ('change', models.FloatField(default=0)),
                ('note', models.CharField(max_length=100, null=True)),
                ('date_reg', models.DateTimeField(null=True)),
                ('date_limit', models.DateTimeField(null=True)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='sale_payments_location', to='api.locationsmodel')),
                ('payment_method', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='sale_payments_payment_method', to='api.paymentmethodsmodel')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='sale_payments_user', to=settings.AUTH_USER_MODEL)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='sale_payments_sale', to='api.salesmodel')),
            ],
            options={
                'db_table': 'sales_payments',
            },
        ),
        migrations.CreateModel(
            name='InventoryModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.FloatField(default=0)),
                ('cost', models.FloatField(default=0)),
                ('quantity', models.FloatField(default=0)),
                ('note', models.CharField(max_length=100, null=True)),
                ('type_inventory', models.IntegerField()),
                ('date_reg', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('user_transfer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='inventory_user_transfer', to=settings.AUTH_USER_MODEL)),
                ('user_transfer_receives', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='inventory_user_transfer_receives', to=settings.AUTH_USER_MODEL)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.inventorytypesmodel')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.locationsmodel')),
                ('location_transfer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='inventory_location_transfer', to='api.locationsmodel')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.productsmodel')),
                ('sale', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='inventory_sale', to='api.salesmodel')),
            ],
            options={
                'db_table': 'inventory',
            },
        ),
        migrations.CreateModel(
            name='StatesModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.countriesmodel')),
            ],
            options={
                'db_table': 'states',
            },
        ),
        migrations.AddField(
            model_name='citiesmodel',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.statesmodel'),
        ),
        migrations.CreateModel(
            name='ExpensesModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('no', models.CharField(unique=True)),
                ('date_limit', models.DateField(null=True)),
                ('date_reg', models.DateTimeField(default=django.utils.timezone.now)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.suppliersmodel')),
            ],
            options={
                'db_table': 'expenses',
            },
        ),
        migrations.AddField(
            model_name='personsmodel',
            name='type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.typesidsmodel'),
        ),
    ]
