# Generated by Django 5.1 on 2024-09-25 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorymodel',
            name='location_transfer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='inventory_location_transfer', to='api.locationsmodel'),
        ),
        migrations.AddField(
            model_name='inventorymodel',
            name='user_transfer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='inventory_user_transfer', to=settings.AUTH_USER_MODEL),
        ),
    ]
