# Generated by Django 5.1 on 2024-09-06 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsmodel',
            name='person',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.RESTRICT, to='api.personsmodel'),
            preserve_default=False,
        ),
    ]
