# Generated by Django 5.1 on 2024-09-10 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personsmodel',
            name='identification_picture',
        ),
        migrations.CreateModel(
            name='IdentificationPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='identification_pictures/')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.personsmodel')),
            ],
        ),
    ]
