# Generated by Django 5.1 on 2024-09-10 15:50

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_personsmodel_identification_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identificationpicture',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.upload_to_identifications),
        ),
    ]
