# Generated by Django 5.1 on 2024-09-27 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_inventorymodel_location_transfer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorymodel',
            name='user_transfer_receives',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='inventory_user_transfer_receives', to=settings.AUTH_USER_MODEL),
        ),
    ]
