# Generated by Django 5.1 on 2024-09-06 01:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_clientsmodel_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personsmodel',
            name='date_reg',
        ),
        migrations.RemoveField(
            model_name='personsmodel',
            name='email',
        ),
        migrations.AddField(
            model_name='clientsmodel',
            name='date_reg',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='clientsmodel',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
