# Generated by Django 5.1 on 2024-09-06 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_personsmodel_date_reg_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personsmodel',
            old_name='types_of_id',
            new_name='type_of_ids',
        ),
        migrations.AlterField(
            model_name='personsmodel',
            name='birthdate',
            field=models.DateField(null=True),
        ),
    ]
