# Generated by Django 5.1 on 2024-09-10 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_identificationpicture_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IdentificationPicture',
            new_name='IdentificationPictures',
        ),
        migrations.AlterModelTable(
            name='identificationpictures',
            table='identification_pictures',
        ),
    ]
