# Generated by Django 5.1 on 2024-09-27 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_inventorymodel_user_transfer_receives'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryTypesModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('type', models.IntegerField()),
            ],
            options={
                'db_table': 'inventory_types',
            },
        ),
        migrations.AlterField(
            model_name='productbrandsmodel',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='productcategoriesmodel',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='inventorymodel',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.inventorytypesmodel'),
        ),
    ]
