# Generated by Django 5.1 on 2024-10-02 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_inventorytypesmodel_alter_productbrandsmodel_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IdentificationImages',
            new_name='IdentificationImagesModel',
        ),
    ]
