# Generated by Django 5.1 on 2024-09-11 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_identificationpicture_identificationpictures_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientContactsModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('relationship', models.CharField(max_length=100)),
                ('fullname', models.CharField()),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField()),
            ],
            options={
                'db_table': 'client_contacts',
            },
        ),
        migrations.CreateModel(
            name='ContactTypesModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'contact_types',
            },
        ),
        migrations.RenameModel(
            old_name='TypesClientsModel',
            new_name='ClientTypesModel',
        ),
        migrations.AlterModelTable(
            name='clienttypesmodel',
            table='client_types',
        ),
    ]
