# Generated by Django 5.1 on 2024-09-07 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_types_of_id_personsmodel_type_of_ids_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citiesmodel',
            name='status',
        ),
        migrations.RemoveField(
            model_name='countriesmodel',
            name='status',
        ),
        migrations.RemoveField(
            model_name='statesmodel',
            name='status',
        ),
    ]
