# Generated by Django 5.1 on 2024-09-11 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_clientcontactsmodel_contacttypesmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcontactsmodel',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='api.contacttypesmodel'),
            preserve_default=False,
        ),
    ]
