# Generated by Django 5.1 on 2024-10-04 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_identificationimages_identificationimagesmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethodsModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField()),
                ('value', models.FloatField(default=0)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'payment_methods',
            },
        ),
    ]
