# Generated by Django 5.1 on 2024-09-08 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_citiesmodel_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientsmodel',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.personsmodel'),
        ),
        migrations.AlterField(
            model_name='personsaddresses',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.addressesmodel'),
        ),
        migrations.AlterField(
            model_name='personsaddresses',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.personsmodel'),
        ),
    ]
