# Generated by Django 5.1 on 2024-09-11 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_clientcontactsmodel_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personsmodel',
            name='addresses',
        ),
        migrations.AddField(
            model_name='addressesmodel',
            name='person',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.personsmodel'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PersonsAddresses',
        ),
    ]
