# Generated by Django 5.1 on 2024-10-08 19:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_salesdetailsmodel_saledetailsmodel_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorymodel',
            name='cost',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='inventorymodel',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='inventorymodel',
            name='sale',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='inventory_sale', to='api.salesmodel'),
        ),
        migrations.AlterField(
            model_name='salepaymentsmodel',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='sales_payments_location', to='api.locationsmodel'),
        ),
        migrations.AlterField(
            model_name='salepaymentsmodel',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='sales_payments_payment_method', to='api.paymentmethodsmodel'),
        ),
        migrations.AlterField(
            model_name='salepaymentsmodel',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='sales_payments_sale', to='api.salesmodel'),
        ),
        migrations.AlterField(
            model_name='salepaymentsmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='sales_payments_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='SaleDetailsModel',
        ),
    ]
