# Generated by Django 5.1 on 2024-09-11 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_personsmodel_addresses_addressesmodel_person_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressesmodel',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='api.personsmodel'),
        ),
    ]
