# Generated by Django 5.1 on 2024-09-17 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_addressesmodel_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuppliersModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=100)),
                ('company_identification', models.CharField(blank=True, max_length=50, null=True)),
                ('company_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('company_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('company_phone_2', models.CharField(blank=True, max_length=20, null=True)),
                ('company_address', models.CharField(blank=True, null=True)),
                ('advisor_fullname', models.CharField(blank=True, null=True)),
                ('advisor_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('advisor_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('advisor_phone_2', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'suppliers',
            },
        ),
        migrations.AlterField(
            model_name='clientcontactsmodel',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='api.clientsmodel'),
        ),
        migrations.AlterField(
            model_name='identificationpictures',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identification_pictures', to='api.personsmodel'),
        ),
    ]
