# Generated by Django 5.1 on 2024-09-18 17:33

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_suppliersmodel_alter_clientcontactsmodel_client_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBrandsModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField()),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'product_brands',
            },
        ),
        migrations.CreateModel(
            name='ProductCategoriesModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField()),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'product_categories',
            },
        ),
        migrations.CreateModel(
            name='TaxesModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField()),
                ('value', models.FloatField(default=0)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'taxes',
            },
        ),
        migrations.AlterField(
            model_name='identificationpictures',
            name='image',
            field=models.ImageField(null=True, upload_to=api.models.upload_to_identifications),
        ),
        migrations.AlterField(
            model_name='suppliersmodel',
            name='advisor_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='suppliersmodel',
            name='advisor_fullname',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='suppliersmodel',
            name='advisor_phone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='suppliersmodel',
            name='advisor_phone_2',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='suppliersmodel',
            name='company_address',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='suppliersmodel',
            name='company_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='suppliersmodel',
            name='company_identification',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='suppliersmodel',
            name='company_phone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='suppliersmodel',
            name='company_phone_2',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='ProductsModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('barcode', models.CharField(max_length=50, null=True)),
                ('name', models.CharField()),
                ('model', models.CharField(max_length=50, null=True)),
                ('note', models.CharField(max_length=100, null=True)),
                ('cost_price', models.FloatField(default=0)),
                ('cash_profit', models.FloatField(default=0)),
                ('cash_price', models.FloatField(default=0)),
                ('credit_price', models.FloatField(default=0)),
                ('credit_profit', models.FloatField(default=0)),
                ('min_stock', models.IntegerField(default=0)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.productbrandsmodel')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.productcategoriesmodel')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.suppliersmodel')),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
