# Generated by Django 5.1 on 2024-09-19 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_productbrandsmodel_productcategoriesmodel_taxesmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsmodel',
            name='tax',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='api.taxesmodel'),
            preserve_default=False,
        ),
    ]
