# Generated by Django 5.1 on 2024-09-19 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_productsmodel_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsmodel',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='api.productbrandsmodel'),
        ),
        migrations.AlterField(
            model_name='productsmodel',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='api.productcategoriesmodel'),
        ),
        migrations.AlterField(
            model_name='productsmodel',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='api.suppliersmodel'),
        ),
        migrations.AlterField(
            model_name='productsmodel',
            name='tax',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='api.taxesmodel'),
        ),
    ]
