# Generated by Django 5.1 on 2024-09-19 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_productsmodel_brand_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsmodel',
            name='tax',
        ),
    ]
