# Generated by Django 5.1 on 2024-09-19 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_productsmodel_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsmodel',
            name='tax',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='api.taxesmodel'),
        ),
    ]
