# Generated by Django 5.1 on 2024-09-23 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_productsmodel_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsmodel',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
