# Generated by Django 5.1 on 2024-09-23 15:54

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_productsmodel_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personsmodel',
            old_name='profile_picture',
            new_name='profile_image',
        ),
        migrations.CreateModel(
            name='IdentificationImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to=api.models.upload_to_identifications)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identification_images', to='api.personsmodel')),
            ],
            options={
                'db_table': 'identification_images',
            },
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to=api.models.upload_to_products)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='product_images', to='api.productsmodel')),
            ],
            options={
                'db_table': 'product_images',
            },
        ),
        migrations.DeleteModel(
            name='IdentificationPictures',
        ),
    ]
