# Generated by Django 5.1 on 2024-09-23 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_rename_profile_picture_personsmodel_profile_image_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductImages',
            new_name='ProductImagesModel',
        ),
    ]
