services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.${APP_MODE}
    volumes:
      - ./backend:/app
    ports:
      - "127.0.0.1:${DJANGO_PORT}:8000"
    env_file:
      - ./.env
    depends_on:
      - db
    networks:
      - cartify_network
    
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.${APP_MODE}
    volumes:
      - ./frontend:/app
    ports:
      - "127.0.0.1:${REACT_PORT}:3000"
    env_file:
      - ./.env
    networks:
      - cartify_network

  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"
    env_file:
      - ./.env
    networks:
      - cartify_network

volumes:
  postgres_data:

networks:
  cartify_network:
    driver: bridge